---
# yamllint disable rule:line-length
AWSTemplateFormatVersion: 2010-09-09
Description: "REA: IAM Stack"

Parameters:
  Project:
    Type: String
    Description: name of the Application

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com

  RolePolicies:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: !Sub '${AWS::StackName}-InstancePolicy'
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "ssm:GetParameter"
              - "ssm:UpdateInstanceInformation"
            Resource:
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/global/*'
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/app/${Project}/${Project}*'
          - Effect: Allow
            Action:
              - cloudwatch:PutMetricAlarm
              - cloudwatch:PutMetricData
              - cloudwatch:ListMetrics
              - ec2:DescribeInstanceStatus
              - ec2:DescribeInstances
              - ec2:DescribeTags
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogStreams
            Resource:
              - arn:aws:logs:*:*:*
      Roles:
        - !Ref Role

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - Ref: Role

Outputs:
  InstanceProfile:
    Description: REA Instance Profile
    Value: !Ref InstanceProfile
    Export:
      Name: !Sub "${AWS::StackName}-instanceprofile"
