---
# yamllint disable rule:line-length
AWSTemplateFormatVersion: 2010-09-09
Description: "REA: Security Stack"

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Vpc ID for the instance
  CidrIPSSH:
    Type: String
    Description: CIDR for ssh access to ec2 instance
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for REA
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 9290
          ToPort: 9292
          CidrIp: 172.31.0.0/16
        - IpProtocol: tcp
          FromPort: 9290
          ToPort: 9292
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref CidrIPSSH

Outputs:
  SecGroup:
    Export:
      Name: !Sub '${AWS::StackName}-sg'
    Value: !Ref InstanceSecurityGroup
